### ISSUE TITLE
Doesn't compile, missing cache/cache.h

### ISSUE THREAD

**Issue by JeffAshtonCT** [GluuFederation/gluu-nginx#1]
From make,

-o objs/addon/src/ngx_http_gluu_ox_module.o \
		/home/jeff/gluu/gluu-nginx/src/ngx_http_gluu_ox_module.c
In file included from /home/jeff/gluu/gluu-nginx/src/ngx_http_gluu_ox_module.c:24:0:
/home/jeff/gluu/gluu-nginx/src/ngx_http_gluu_ox_module.h:34:25: fatal error: cache/cache.h: No such file or directory
 #include "cache/cache.h"

**Comment by JeffAshtonCT** [comment]
andriybobyr, are we just missing some of your local changes?

**Comment by willow9886** [comment]
Jeff,

We had to pause development of this plugin. I just updated the [readme](https://github.com/GluuFederation/gluu-nginx) with an explanation. This is an important development priority for us, just one that is not currently sufficiently funded. Hopefully can get back to work on it later this year. 

Thanks for your understanding.
